baseURL: "https://TrungNgoVan.github.io/blog/"
languageCode: en-us
title: 🐳 I'm nvtrung
theme: PaperMod

params:
  author: Ngo Van Trung
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShareButtons: ["facebook", "twitter"]
  enableEmoji: true
  enableInlineShortcodes: true
  showtoc: true
menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 11
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 12
    - identifier: about
      name: About
      url: /about/
      weight: 13
    - name: Github
      url: https://github.com/TrungNgoVan
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
