baseURL: "https://TrungNgoVan.github.io/blog/"
languageCode: en-us
title: I'm nvtrung
paginate: 5
theme: PaperMod

params:
  author: Ngo Van Trung
  ShowReadingTime: true
  # ShowBreadCrumbs: true
  ShowShareButtons: true
  ShareButtons: ["facebook", "twitter"]
  enableEmoji: true
  enableInlineShortcodes: true
  Showtoc: true
  assets:
    favicon: "/blog/favicon.ico"
    favicon16x16: "/blog/favicon-16x16.png"
    favicon32x32: "/blog/favicon-32x32.png"
    apple_touch_icon: "/blog/apple-touch-icon.png"
    disableHLJS: true
  editPost:
    URL: "https://github.com/TrungNgoVan/blog/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  cover:
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  label:
    text: "🐳 Tập vở của Henry"
    # icon: ./static/apple-touch-icon.png
    # iconHeight: 35
  homeInfoParams:
    Title: "Hello 👻"
    Content: Đây là blog của mình 🐳

  socialIcons:
    - name: facebook
      url: "https://www.facebook.com/nvtrung2601/"
    - name: github
      url: "https://github.com/TrungNgoVan"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    guessSyntax: true
    lineNos: true
menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 5
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 3
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: CV
      name: CV
      url: /cv.pdf
      weight: 6
    # - name: Github
    #   url: https://github.com/TrungNgoVan

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
