baseURL = 'https://TrungNgoVan.github.io/blog/'
languageCode = 'en-us'
title = "I'm nvtrung"
theme = 'PaperMod'
[params]
    showReadingTime = true
    showBreadCrumbs = true
    showCodeCopyButtons =true

[languages.en.menu]
    [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"


